/**
 * Operator audit-key resolution — the honest default between two extremes:
 *
 *   `env`          — AIRMCP_AUDIT_HMAC_KEY is set. Strongest: the secret lives
 *                    outside the audit store, works for CI/daemon deployments,
 *                    and enables cross-machine verification (move audit.jsonl
 *                    to another host and verify with the same key).
 *   `keyfile`      — a random key generated by `npx airmcp init` and stored at
 *                    `<store>/audit-hmac.key` (0600, dir 0700). Non-derivable
 *                    (unlike the host fallback, forging requires actually
 *                    reading the file, not re-deriving it from host facts) but
 *                    still readable by any same-user process — for
 *                    non-repudiation against a local attacker, use `env`.
 *   `host-derived` — nothing configured; audit.ts falls back to
 *                    `airmcp-audit::<hostname>::<platform>`. Tamper-EVIDENT
 *                    only: anyone with shell access can re-derive it.
 *
 * Kept OUT of audit.ts so the fail-closed chain writer stays focused on the
 * chain itself: audit.ts calls {@link resolveOperatorKeySync} exactly once at
 * module load, because the chain key must be stable for the life of the
 * process — a mid-flight key change would break the chain it is writing.
 */
import { chmodSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { randomBytes } from "node:crypto";
import { PATHS } from "./constants.js";

export const AUDIT_KEY_FILENAME = "audit-hmac.key";

export type OperatorKeySource = "env" | "keyfile" | "host-derived";

export function operatorKeyFilePath(): string {
  return join(PATHS.VECTOR_STORE, AUDIT_KEY_FILENAME);
}

/** Reject key files that are clearly not key material (truncated writes,
 *  accidental touch). Generated keys are 64 hex chars; anything under 32
 *  chars falls back to host-derived with a stderr warning. */
const MIN_KEYFILE_CHARS = 32;

/**
 * Resolve the operator audit key. Pure read — no generation, no writes.
 * Priority: env (verbatim, matching the historical contract) > key file
 * (trimmed) > none. Unreadable and too-short key files both resolve to
 * `host-derived`; the too-short case warns once so a truncated file is not
 * silently equivalent to no file.
 */
export function resolveOperatorKeySync():
  { key: string; source: "env" | "keyfile" } | { key: null; source: "host-derived" } {
  const env = process.env.AIRMCP_AUDIT_HMAC_KEY ?? "";
  if (env.length > 0) return { key: env, source: "env" };
  const path = operatorKeyFilePath();
  try {
    const raw = readFileSync(path, "utf-8").trim();
    if (raw.length >= MIN_KEYFILE_CHARS) {
      // Mirror the perms hygiene applied to audit.jsonl: a manually created or
      // drifted 0644 key file is quietly narrowed back to owner-only. Repair
      // is best-effort — a failure must not downgrade an otherwise valid key.
      try {
        if ((statSync(path).mode & 0o077) !== 0) {
          chmodSync(path, 0o600);
          console.error(`[AirMCP] audit key file ${path} was group/other-readable — tightened to 0600`);
        }
      } catch {
        /* stat/chmod race — keep the key */
      }
      return { key: raw, source: "keyfile" };
    }
    if (raw.length > 0) {
      console.error(
        `[AirMCP] audit key file ${path} is shorter than ${MIN_KEYFILE_CHARS} chars — ` +
          `ignoring it and falling back to the host-derived key`,
      );
    }
  } catch (err) {
    // ENOENT is the normal no-keyfile case. Anything else (EACCES, I/O) must
    // NOT downgrade silently: a chain sealed with the unreadable key would
    // then scan as tampered under the host-derived key.
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") {
      console.error(
        `[AirMCP] audit key file ${path} exists but could not be read (${(err as NodeJS.ErrnoException).code ?? "error"}) — ` +
          `falling back to the host-derived key; a chain sealed with the file key will report tampered`,
      );
    }
  }
  return { key: null, source: "host-derived" };
}

/**
 * True when the store already holds sealed audit state (any `audit*.jsonl`
 * chain file or the checkpoint). Introducing a new key over such a chain
 * would make whole-chain verification replay old rows under the wrong key —
 * i.e. a false `tampered` verdict plus fail-closed audit authority — so key
 * generation refuses while this is true and the operator must archive the
 * old chain explicitly first.
 */
export function hasExistingAuditChain(): boolean {
  const dir = PATHS.VECTOR_STORE;
  try {
    if (existsSync(join(dir, "audit.checkpoint"))) return true;
    return readdirSync(dir).some((name) => name.startsWith("audit") && name.endsWith(".jsonl"));
  } catch {
    return false; // no store dir yet — trivially no chain
  }
}

/**
 * Ensure an operator key exists for this store, generating one when neither
 * the env var nor a valid key file is present. Never overwrites an existing
 * file — an existing-but-invalid key file is surfaced as `host-derived` with
 * `created:false` so the caller can point the operator at the exact path
 * instead of us silently clobbering something we did not write.
 *
 * Refuses (`blockedByExistingChain`) when the store already holds a sealed
 * chain: rows HMAC'd under the host-derived key would fail whole-chain
 * verification under the new key — a false `tampered` verdict that also
 * fail-closes audit authority. Upgrading an existing store is an explicit
 * operator action: archive `<store>/audit*.jsonl` + `audit.checkpoint`
 * elsewhere (the old chain stays verifiable with this host's derived key),
 * then rerun init.
 */
export function ensureOperatorKeyFile(): {
  source: OperatorKeySource;
  path: string;
  created: boolean;
  blockedByExistingChain?: boolean;
} {
  const path = operatorKeyFilePath();
  const resolved = resolveOperatorKeySync();
  if (resolved.source !== "host-derived") return { source: resolved.source, path, created: false };
  if (hasExistingAuditChain()) {
    return { source: "host-derived", path, created: false, blockedByExistingChain: true };
  }
  try {
    mkdirSync(PATHS.VECTOR_STORE, { recursive: true, mode: 0o700 });
    // `wx` fails on an existing file, so a concurrent init cannot interleave
    // a read-modify-write and two processes cannot end up with different keys.
    writeFileSync(path, randomBytes(32).toString("hex") + "\n", { mode: 0o600, flag: "wx" });
    return { source: "keyfile", path, created: true };
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "EEXIST") {
      // Lost the race (another init created it) or an invalid file already
      // occupies the path — re-resolve and report what is actually there.
      const after = resolveOperatorKeySync();
      return { source: after.source, path, created: false };
    }
    throw err;
  }
}
