#!/usr/bin/env node
/**
 * count-stats.mjs — Single source of truth for tool/module/prompt/resource counts.
 *
 * Counts are derived from source code, then propagated to all documentation.
 *
 * Usage:
 *   node scripts/count-stats.mjs          # print current counts
 *   node scripts/count-stats.mjs --check  # verify docs match source (CI)
 *   node scripts/count-stats.mjs --sync   # update all docs to match source
 */

import { readFileSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { syncFile as syncAnchoredFile } from "./lib/sync-file.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src");
const mode = process.argv.includes("--check") ? "check" : process.argv.includes("--sync") ? "sync" : "print";

// ── Count from source ──────────────────────────────────────────────

function countInDir(dir, pattern) {
  let count = 0;
  function walk(d) {
    for (const entry of readdirSync(d, { withFileTypes: true })) {
      const full = join(d, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith(".ts")) {
        const content = readFileSync(full, "utf-8");
        const matches = content.match(pattern);
        if (matches) count += matches.length;
      }
    }
  }
  walk(dir);
  return count;
}

// Tool count is the authoritative runtime surface from the generated manifest
// (docs/tool-manifest.json): it includes the `server.registerTool()` tools PLUS
// the dynamically-registered + `registerAppTool()` tools a source regex on
// `registerTool(` alone misses. The manifest is regenerated by `gen:manifest`
// (and guarded by gen:manifest:check) — the single source of truth for what the
// server actually exposes. Fall back to tools[].length, then 0 on a fresh
// checkout so --check flags drift loudly instead of crashing.
const MANIFEST_PATH = join(ROOT, "docs", "tool-manifest.json");
let tools = 0;
if (existsSync(MANIFEST_PATH)) {
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf-8"));
  tools = typeof manifest.toolCount === "number" ? manifest.toolCount : (manifest.tools?.length ?? 0);
}
const prompts = countInDir(SRC, /server\.prompt\(/g);

// AppIntent count — auto-generated from docs/tool-manifest.json by
// scripts/gen-swift-intents.mjs. The generated file is the source of
// truth; README/RFC/docs strings drift behind it and that drift has
// repeatedly been the leading example of "docs lie" in audits. Count
// every `: AppIntent {` conformance in the generated Swift file. If
// the file is missing (fresh checkout pre-codegen) we report 0 rather
// than crashing — the --check mode will then flag every doc as stale,
// which is the correct loud signal.
const INTENTS_PATH = join(ROOT, "swift", "Sources", "AirMCPKit", "Generated", "MCPIntents.swift");
let appIntents = 0;
let snippetViews = 0;
let appEnums = 0;
if (existsSync(INTENTS_PATH)) {
  const intentsContent = readFileSync(INTENTS_PATH, "utf-8");
  // `: AppIntent {` matches the protocol conformance opening. `: AppIntent,`
  // is unused in the generator output today but kept in the alternation
  // so a future "conforms to AppIntent + Sendable" pattern doesn't silently
  // start under-counting.
  const matches = intentsContent.match(/:\s*AppIntent\s*[\{,]/g);
  appIntents = matches ? matches.length : 0;
  const snippetMatches = intentsContent.match(/public struct MCP\w+SnippetView:\s*View/g);
  snippetViews = snippetMatches ? snippetMatches.length : 0;
  const enumMatches = intentsContent.match(/public enum \w+:\s*String,\s*AppEnum/g);
  appEnums = enumMatches ? enumMatches.length : 0;
}

// MCP Apps (interactive UI views via @modelcontextprotocol/ext-apps).
// Registered via `registerAppTool` and already included in the manifest's
// toolCount above; surfaced separately here so module-health audits don't
// mis-flag `src/apps/` as a 0-tool ghost module.
const mcpApps = countInDir(SRC, /registerAppTool\(/g);

const resContent = readFileSync(join(SRC, "shared", "resources.ts"), "utf-8");
const resLines = resContent.split("\n");
let resources = 0;
let inRegisterFn = false;
for (const line of resLines) {
  if (/^export function registerResources/.test(line)) inRegisterFn = true;
  if (inRegisterFn) {
    if (/jsonResource\(server,/.test(line)) resources++;
    else if (/server\.registerResource\(/.test(line)) resources++;
  }
}

// Count the whole module catalog from MODULE_MANIFEST (modules.ts) — including
// opt-in modules (spatial_prep, webhooks, powerautomate) that are absent from
// the standard-profile MODULE_NAMES. Uses the SAME pattern as the
// tool-count-drift test so the doc count and that guard can never diverge.
const modulesContent = readFileSync(join(SRC, "shared", "modules.ts"), "utf-8");
const modules = (modulesContent.match(/\bname:\s*"[a-z0-9_-]+"/g) ?? []).length;

const stats = { tools, prompts, resources, modules, mcpApps, appIntents, snippetViews, appEnums };

// ── Print mode ─────────────────────────────────────────────────────

if (mode === "print") {
  console.log(JSON.stringify(stats, null, 2));
  process.exit(0);
}

// ── Shared helpers for check & sync ────────────────────────────────

let dirty = false;
let changedAny = false;
let fatal = false;

/**
 * Apply numeric replacements to a file.
 * Each replacement: { pattern: RegExp with (\d+) capture group, value: number }
 */
function syncFile(relPath, replacements) {
  const result = syncAnchoredFile(ROOT, relPath, replacements, { mode });
  dirty ||= result.dirty;
  changedAny ||= result.changed;
  fatal ||= result.fatal;
}

// ── Run ────────────────────────────────────────────────────────────

console.log(
  `\nStats ${mode}: ${tools} tools, ${prompts} prompts, ${resources} resources, ${modules} modules, ${mcpApps} MCP Apps, ${appIntents} AppIntents, ${snippetViews} snippets, ${appEnums} AppEnums\n`,
);

// README.md — also picks up the two lines audits keep flagging:
//   "**229 Shortcuts / Siri AppIntents**" → reconciled with generated file
//   "**34 prompts + 14 YAML skill built-ins**" → reconciled with src count
syncFile("README.md", [
  { pattern: /The catalog is broad: (\d+) tools across/g, value: tools },
  { pattern: /tools across (\d+) modules/g, value: modules },
  { pattern: /\*\*(\d+) tools\*\*/, value: tools },
  { pattern: /(\d+) modules\)/g, value: modules },
  { pattern: /(\d+) Apple apps/g, value: modules },
  { pattern: /(\d+) Shortcuts\/AppIntents/g, value: appIntents },
  { pattern: /\*\*(\d+) Shortcuts \/ Siri AppIntents\*\*/, value: appIntents },
  { pattern: /Current generated surfaces: (\d+) Shortcuts \/ Siri AppIntents/g, value: appIntents },
  { pattern: /(\d+) Interactive Snippet views/g, value: snippetViews },
  { pattern: /and (\d+) AppEnum pickers/g, value: appEnums },
  { pattern: /(\d+) auto-generated AppIntents/g, value: appIntents },
  { pattern: /\*\*(\d+) prompts \+ /, value: prompts },
]);

// AGENTS.md
syncFile(".github/AGENTS.md", [
  { pattern: /\*\*(\d+) tools\*\*/, value: tools },
  { pattern: /(\d+) modules/, value: modules },
  { pattern: /\*\*(\d+) prompts\*\*/, value: prompts },
  { pattern: /\*\*(\d+) [\w-]*resources\*\*/, value: resources },
]);

// Docs site pages
const docsPages = [
  "docs/site/src/content/docs/modules/overview.md",
  "docs/site/src/content/docs/architecture/overview.md",
  "docs/site/src/content/docs/getting-started/installation.md",
  "docs/site/src/content/docs/getting-started/configuration.md",
  "docs/site/src/content/docs/contributing/testing.md",
];
for (const page of docsPages) {
  syncFile(page, [
    { pattern: /(\d+) modules/g, value: modules },
    { pattern: /All (\d+) AirMCP modules/g, value: modules },
    { pattern: /approximately (\d+) tools/g, value: tools },
    { pattern: /all (\d+) tools/g, value: tools },
    { pattern: /contains (\d+) tools/g, value: tools },
  ]);
}

syncFile("docs/site/src/content/docs/index.mdx", [
  { pattern: /— (\d+) modules, \d+ tools/g, value: modules },
  { pattern: /— \d+ modules, (\d+) tools/g, value: tools },
  { pattern: /<Card title="(\d+) Modules"/, value: modules },
  { pattern: /<Card title="(\d+) Tools"/, value: tools },
]);

// MCPB manifest template — the long_description string lives in the user
// install dialog, so a stale count is highly visible. Guard the tool /
// module / AppIntent counts so the blurb can't re-drift (e.g. the old
// "270+ tools" that slipped past this guard before).
syncFile("mcpb/manifest.template.json", [
  { pattern: /(\d+) tools across/g, value: tools },
  { pattern: /across (\d+) modules/g, value: modules },
  { pattern: /(\d+) auto-generated Apple App Intents/g, value: appIntents },
  { pattern: /Load all (\d+) modules on startup/g, value: modules },
]);

// Other docs
syncFile("docs/skills.md", [
  { pattern: /(\d+) tools/g, value: tools },
  { pattern: /(\d+) modules/g, value: modules },
]);
syncFile("docs/shortcuts.md", [{ pattern: /(\d+) tools are auto-registered/g, value: tools }]);
syncFile("docs/REGISTRY_SUBMISSIONS.md", [{ pattern: /(\d+) AppIntents/g, value: appIntents }]);
syncFile("docs/REGISTRY_SUBMISSIONS.md", [
  { pattern: /(\d+) tools across/g, value: tools },
  { pattern: /across (\d+) modules/g, value: modules },
  { pattern: /\((\d+) tools, \d+ modules/g, value: tools },
  { pattern: /, (\d+) modules, curated workflow catalog/g, value: modules },
]);
syncFile("docs/TERMS_OF_SERVICE.md", [
  { pattern: /(\d+) tools/g, value: tools },
  { pattern: /(\d+) modules/g, value: modules },
]);
syncFile("docs/environment.md", [{ pattern: /Send all (\d+) tools/g, value: tools }]);
syncFile("docs/mcpb.md", [{ pattern: /Load all (\d+) modules on startup/g, value: modules }]);

// Landing page — only match aggregate counts, not per-module badges.
syncFile("docs/index.html", [
  { pattern: /— (\d+) modules, \d+ tools/g, value: modules },
  { pattern: /— \d+ modules, (\d+) tools/g, value: tools },
  { pattern: /(\d+) Apple modules, \d+ tools/g, value: modules },
  { pattern: /\d+ Apple modules, (\d+) tools/g, value: tools },
  {
    pattern:
      /text-2xl font-bold tracking-tight">(\d+)<\/div>\s*<div class="text-xs opacity-35 mt-1" data-i18n="stat_modules"/,
    value: modules,
  },
  {
    pattern:
      /text-2xl font-bold tracking-tight">(\d+)<\/div>\s*<div class="text-xs opacity-35 mt-1" data-i18n="stat_tools"/,
    value: tools,
  },
  {
    pattern:
      /text-2xl font-bold tracking-tight">(\d+)<\/div>\s*<div class="text-xs opacity-35 mt-1" data-i18n="stat_prompts"/,
    value: prompts,
  },
  { pattern: /with (\d+) tools across/g, value: tools },
  { pattern: /across (\d+) modules/g, value: modules },
  { pattern: /hero_sub">(\d+) tools/g, value: tools },
  { pattern: /tryit_footer">(\d+) tools/g, value: tools },
  { pattern: /why_1_title">(\d+) tools/g, value: tools },
]);

// Registry metadata
const registryPattern = [
  { pattern: /(\d+) tools across/g, value: tools, required: true, label: "tool count" },
  { pattern: /across (\d+) modules/g, value: modules, required: true, label: "module count" },
];
syncFile("mcp.json", registryPattern);
syncFile("glama.json", registryPattern);
syncFile("smithery.yaml", registryPattern);
// .claude-plugin/plugin.json description carries the counts on the public
// marketplace listing page — same drift class as the registry manifests.
syncFile(".claude-plugin/plugin.json", registryPattern);
// Anthropic MCP Registry manifest — only the description carries
// the counts (version/package fields live outside the pattern scope).
syncFile("server.json", [
  { pattern: /(\d+) tools across/g, value: tools, required: true, label: "tool count" },
  { pattern: /across (\d+) modules/g, value: modules, required: true, label: "module count" },
]);

// Locale files — each uses different words for "modules"
const localeDir = join(ROOT, "docs", "locales");
if (existsSync(localeDir)) {
  const moduleWords = /(\d+)([\s\u00a0]*(?:modules?|개 모듈|モジュール|个模块|個模組|Module|Modulen|m[oó]dulos))/g;
  const moduleKeyWords = /(\d+)([\s\u00a0]*(?:modules?|개 모듈|モジュール|个模块|個模組|Module|Modulen|m[oó]dulos))/;
  const toolKeyWords =
    /(\d+)([\s\u00a0]*(?:tools?|Tools|개 툴|개 도구|ツール|个工具|個工具|Werkzeuge|herramientas|outils|ferramentas))/;
  for (const f of readdirSync(localeDir).filter((f) => f.endsWith(".json"))) {
    syncFile(`docs/locales/${f}`, [
      { pattern: moduleWords, value: modules },
      { pattern: new RegExp(`"meta_description": "[^"]*?${moduleKeyWords.source}`), value: modules },
      { pattern: new RegExp(`"meta_description": "[^"]*?${toolKeyWords.source}`), value: tools },
      { pattern: new RegExp(`"why_1_title": "[^"]*?${moduleKeyWords.source}`), value: modules },
      { pattern: new RegExp(`"why_1_title": "[^"]*?${toolKeyWords.source}`), value: tools },
      { pattern: new RegExp(`"tryit_footer": "${toolKeyWords.source}`), value: tools },
    ]);
  }
}

console.log("");

if (dirty) {
  if (fatal) {
    console.error("Stats sync anchors missing. Restore the anchors or update scripts/count-stats.mjs.");
  } else {
    console.error("Stats mismatch detected. Run: node scripts/count-stats.mjs --sync");
  }
  process.exit(1);
}

if (mode === "sync" && !changedAny) {
  console.log("All files already in sync.");
}
